// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdlkpuwohpbwyqzcgsjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbGtwdXdvaHBid3lxemNnc2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjQ5NjYsImV4cCI6MjA3MTU0MDk2Nn0.6irqwnDYazUCpI4Ooaj2w81HLxKWwZK8CLJ-PAK7cRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});